development:
  adapter: postgresql
  encoding: unicode
  database: mcalilly_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mcalilly_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mcalilly_production
  pool: 5
  password:
